# Generated by Django 4.1.3 on 2023-01-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsupplier',
            name='business_name',
            field=models.CharField(max_length=150, verbose_name='Nombre de Empresa (Razón Social)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='business_name',
            field=models.CharField(max_length=150, verbose_name='Nombre de Empresa (Razón Social)'),
        ),
    ]
