# Generated by Django 4.1.3 on 2023-01-05 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0002_alter_historicalsupplier_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='expense_manager.expensecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='expense_manager.expensecategory'),
        ),
    ]
