# Generated by Django 4.1.3 on 2023-01-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0003_expense_category_historicalexpense_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='expense_category',
        ),
        migrations.RenameField(
            model_name='historicalexpense',
            old_name='category',
            new_name='expense_category',
        ),
    ]
